[package]
name = "prompt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
chrono = "0.4.19"
git2 = "0.14.4"
hostname = "0.3.0"
owo-colors = "3.4.0"
