#!/bin/bash

DB_ROOT=~/.db/
DB_SETTINGS_BASE="$(realpath "$(dirname "$BASH_SOURCE")"/../)"
DB_SETTINGS_VIM_BASE="$DB_SETTINGS_BASE/vim/"
DB_SETTINGS_BASH_BASE="$DB_SETTINGS_BASE/bash/"

export DB_SETTINGS_BASE
export DB_SETTINGS_VIM_BASE
export DB_SETTINGS_BASH_BASE
export DB_ROOT

